export const users = [
  {
    _id: '66af83b1b71f922ae31720f5',
    index: 0,
    guid: '61139e17-4b8f-48d5-a6d9-14b29ba09fa1',
    isActive: false,
    balance: '$1,675.96',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'brown',
    name: 'Clarissa Holman',
    gender: 'female',
    company: 'QUIZKA',
    email: 'clarissaholman@quizka.com',
    phone: '+1 (846) 567-3918',
    address: '173 Corbin Place, Hartsville/Hartley, Louisiana, 9995',
    about:
      'Do dolore non dolore amet ipsum tempor consequat ut. Sint excepteur irure cillum anim. Duis est amet ipsum veniam laborum voluptate culpa aute deserunt proident elit aliquip nostrud ullamco. Eu incididunt voluptate magna sunt adipisicing nulla non non est. Fugiat anim minim exercitation sunt ipsum eiusmod id ut velit culpa esse eiusmod dolore cupidatat. Sint ullamco Lorem consectetur sunt laborum magna elit cupidatat reprehenderit reprehenderit.\r\n',
    registered: '2016-06-04T09:15:10 -03:00',
    latitude: -49.049303,
    longitude: 123.115662,
    tags: ['ut', 'ut', 'ea', 'qui', 'commodo', 'aute', 'ullamco'],
    friends: [
      {
        id: 0,
        name: 'Juana Dickerson',
      },
      {
        id: 1,
        name: 'Janis Guy',
      },
      {
        id: 2,
        name: 'Cline Gill',
      },
    ],
    greeting: 'Hello, Clarissa Holman! You have 5 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66af83b162dc59c0a0ec369a',
    index: 1,
    guid: '6b20eacd-52e2-4331-8e3e-6fe08561016b',
    isActive: true,
    balance: '$2,058.81',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'brown',
    name: 'Bauer Robles',
    gender: 'male',
    company: 'ENDIPIN',
    email: 'bauerrobles@endipin.com',
    phone: '+1 (863) 469-2552',
    address: '596 Visitation Place, Baden, Illinois, 9839',
    about:
      'Tempor sit sit esse eiusmod commodo esse cupidatat. Ad mollit eu non occaecat quis sunt ipsum. Officia eu sunt cillum sint ad veniam in dolore laboris excepteur esse commodo.\r\n',
    registered: '2020-07-08T12:19:57 -03:00',
    latitude: 66.821796,
    longitude: -159.301618,
    tags: [
      'occaecat',
      'veniam',
      'aliqua',
      'occaecat',
      'reprehenderit',
      'nulla',
      'qui',
    ],
    friends: [
      {
        id: 0,
        name: 'Dixie Hendricks',
      },
      {
        id: 1,
        name: 'Betsy Mcneil',
      },
      {
        id: 2,
        name: 'Shields Bolton',
      },
    ],
    greeting: 'Hello, Bauer Robles! You have 1 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66af83b16fddf65231347e9a',
    index: 2,
    guid: 'f9074515-5945-49eb-b451-8439df704f3f',
    isActive: false,
    balance: '$2,195.46',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'green',
    name: 'Suzanne Hull',
    gender: 'female',
    company: 'ENERSAVE',
    email: 'suzannehull@enersave.com',
    phone: '+1 (821) 451-2018',
    address: '687 Burnett Street, Ada, Arkansas, 2890',
    about:
      'Velit id fugiat reprehenderit pariatur dolor amet velit. Esse anim culpa eiusmod occaecat et consequat reprehenderit elit ut do do excepteur dolor. Non voluptate nulla sunt laboris nulla fugiat laborum elit ea et. Cillum magna ad magna velit adipisicing nostrud sint consectetur ea veniam dolor excepteur aliquip. Reprehenderit fugiat ea elit elit consequat et. Amet incididunt aute nulla ea nisi ea officia.\r\n',
    registered: '2016-05-07T05:15:37 -03:00',
    latitude: 84.333781,
    longitude: 18.700329,
    tags: ['ea', 'sint', 'enim', 'veniam', 'duis', 'duis', 'ex'],
    friends: [
      {
        id: 0,
        name: 'Gladys Hancock',
      },
      {
        id: 1,
        name: 'Tonia Riley',
      },
      {
        id: 2,
        name: 'Brenda Goodwin',
      },
    ],
    greeting: 'Hello, Suzanne Hull! You have 1 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66af83b11d273097c6ace620',
    index: 3,
    guid: 'f273bc67-04bc-4116-9043-cfd87db60b61',
    isActive: false,
    balance: '$2,434.62',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: 'Berry Oconnor',
    gender: 'male',
    company: 'EXTRAGEN',
    email: 'berryoconnor@extragen.com',
    phone: '+1 (933) 502-2231',
    address: '994 Wyona Street, Sperryville, Iowa, 1105',
    about:
      'Reprehenderit in adipisicing reprehenderit in dolor in deserunt et consectetur officia. Laboris anim enim est pariatur labore. Enim laboris minim quis irure veniam incididunt aliqua in cillum irure culpa nostrud sunt. Quis elit et ullamco incididunt nostrud. Ex labore reprehenderit minim proident cupidatat eu sit anim fugiat eu ut nisi Lorem.\r\n',
    registered: '2022-08-15T04:41:37 -03:00',
    latitude: 49.114134,
    longitude: -46.993535,
    tags: [
      'irure',
      'incididunt',
      'incididunt',
      'reprehenderit',
      'ex',
      'nisi',
      'ad',
    ],
    friends: [
      {
        id: 0,
        name: 'Ivy Barnett',
      },
      {
        id: 1,
        name: 'Bray Torres',
      },
      {
        id: 2,
        name: 'Pugh Owen',
      },
    ],
    greeting: 'Hello, Berry Oconnor! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66af83b19903a37fafffb241',
    index: 4,
    guid: '7601fd3e-e0b1-492e-9a1f-83bea8fcac40',
    isActive: true,
    balance: '$3,681.35',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'green',
    name: 'Carr Church',
    gender: 'male',
    company: 'TECHMANIA',
    email: 'carrchurch@techmania.com',
    phone: '+1 (966) 503-3863',
    address: '247 Hunts Lane, Savannah, Oregon, 8214',
    about:
      'Aliqua est aute do aute id. Cillum esse pariatur anim ullamco sint magna voluptate deserunt. Fugiat adipisicing irure tempor amet. Consequat anim exercitation adipisicing ea. Esse laborum labore aliquip ea deserunt officia voluptate nostrud ex quis in est do officia. Aute esse sunt aute elit magna eiusmod est nulla adipisicing dolor magna laboris.\r\n',
    registered: '2023-10-30T08:17:21 -02:00',
    latitude: -5.187822,
    longitude: 141.316257,
    tags: ['veniam', 'irure', 'non', 'tempor', 'culpa', 'nostrud', 'voluptate'],
    friends: [
      {
        id: 0,
        name: 'Imogene Bonner',
      },
      {
        id: 1,
        name: 'Ola Ruiz',
      },
      {
        id: 2,
        name: 'Angelita Walker',
      },
    ],
    greeting: 'Hello, Carr Church! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
];
